name: vb_app
description: "VidyaBox by SunoKitaab"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^8.1.0
  flutter_screenutil: ^5.9.0
  sms_autofill: ^2.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.0.0
  lottie: ^3.0.0
  url_launcher: ^6.0.9
  intl: ^0.18.0
  connectivity_plus: ^6.0.2
  flare_splash_screen: ^4.0.0
  cupertino_icons: ^1.0.2
  confetti: ^0.7.0
  extended_nested_scroll_view: ^6.2.1
  dio_smart_retry: ^6.0.0
  intl_phone_field: ^3.1.0
  shared_preferences: ^2.0.7
  auto_route: ^5.0.4
  get_it: ^7.2.0
  dio: ^5.4.3
  drift_sqflite: ^2.0.1
  flutter_localizations:
    sdk: flutter
  animated_theme_switcher: ^2.0.7
  device_info_plus: ^9.0.3
  equatable: ^2.0.2
  flutter_svg: ^2.0.9
  sqlite3_flutter_libs: ^0.5.0


dev_dependencies:
  build_runner: any
  build_runner_core: ^7.2.9
  auto_route_generator: ^5.0.3
  drift_dev: ^2.9.0
  analyzer: ^5.13.0

flutter_intl:
  enabled: true
  class_name: AppLocalizations


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/logo/
    - assets/audios/
    - assets/icons/

  fonts:
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Martel-Regular
      fonts:
        - asset: assets/fonts/Martel-Regular.ttf

    - family: Martel-Bold
      fonts:
        - asset: assets/fonts/Martel-Bold.ttf

    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: Montserrat-ExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf

    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
